exports.seed = knex =>
  knex('items').insert([
    {
      id: 1,
      name: 'Apple',
      user_id: '2',
      dateCreated: '13/07 13:00',
      expiryDate: '3/08 13:00',
      location: 'Waterview, Auckland',
      quantity: '6',
      description: 'good shape',
      email: 'vegelover@gmail.com',
      isClaimed: false,
      img: '/images/apple.jpg'

    },
    {
      id: 2,
      name: 'Potato',
      user_id: '3',
      dateCreated: '13/08 13:00',
      expiryDate: '3/09 10:00',
      location: 'Avondale, Auckland',
      quantity: '9',
      description: 'a bit bruised',
      email: 'eatwell@gmail.com',
      isClaimed: false,
      img: '/images/potatoes.jpeg'
    },
    {
      id: 3,
      name: 'Onion',
      user_id: '3',
      dateCreated: '14/08 13:00',
      expiryDate: '3/09 10:00',
      location: 'Takapuna, Auckland',
      quantity: '9',
      description: 'good',
      email: 'eatwellbeing@gmail.com',
      isClaimed: false,
      img: '/images/onion.jpeg'
    },
    {
      id: 4,
      name: 'Pork Chop',
      user_id: '3',
      dateCreated: '14/10 9:00',
      expiryDate: '17/10 10:00',
      location: 'Mission Bay, Auckland',
      quantity: '1',
      description: 'fresh pork chop needs to be picked up by today.',
      email: 'Tj@hotmail.com',
      isClaimed: false,
      img: '/images/.jpeg'
    },
    {
      id: 5,
      name: 'Pasta',
      user_id: '3',
      dateCreated: '12/07 18:40',
      expiryDate: '12/10 10:00',
      location: 'New Lynn, Auckland',
      quantity: '5',
      description: 'Unwanted dried pasta',
      email: 'wsmith@gmail.com',
      isClaimed: false,
      img: '/images/pasta.jpeg'
    },
    {
      id: 6,
      name: 'Onion',
      user_id: '3',
      dateCreated: '14/08 13:00',
      expiryDate: '3/09 10:00',
      location: 'Takapuna, Auckland',
      quantity: '9',
      description: 'good',
      email: 'eatwellbeing@gmail.com',
      isClaimed: false,
      img: '/images/onion.jpeg'
    },
    {
      id: 7,
      name: 'Self Rising Flour',
      user_id: '3',
      dateCreated: '1/06 9:30',
      expiryDate: '1/10 10:00',
      location: 'Manukau, Auckland',
      quantity: '5',
      description: 'N/A',
      email: 'caterall@hotmail.com',
      isClaimed: true,
      img: '/images/onion.jpeg'
    },
    {
      id: 8,
      name: 'Almonds',
      user_id: '3',
      dateCreated: '1/01 19:45',
      expiryDate: '3/09 10:00',
      location: 'Papakura, Auckland',
      quantity: '500g',
      description: 'Freshly Toasted Almonds',
      email: 'localproduce@yahoo.com',
      isClaimed: false,
      img: '/images/onion.jpeg'
    },
    {
      id: 9,
      name: 'G/F loaf',
      user_id: '3',
      dateCreated: '3/02 13:00',
      expiryDate: '14/02 10:00',
      location: 'Albany, Auckland',
      quantity: '1',
      description: 'Freezable G/F bread',
      email: 'qualitybakery@gmail.com',
      isClaimed: false,
      img: '/images/onion.jpeg'
    },
    {
      id: 10,
      name: 'Canola Oil',
      user_id: '3',
      dateCreated: '14/5 21:00',
      expiryDate: '13/12 10:00',
      location: 'Massey, Auckland',
      quantity: '5 Liter',
      description: 'unwanted unused oil',
      email: 'serviceproducts@xtra.com',
      isClaimed: true,
      img: '/images/onion.jpeg'
    },
    {
      id: 11,
      name: 'Drum Sticks',
      user_id: '3',
      dateCreated: '14/08 13:00',
      expiryDate: '3/09 10:00',
      location: 'Penrose, Auckland',
      quantity: '1 Kg',
      description: 'decided to go Vegetarian',
      email: 'kokoaono@hotmail.com',
      isClaimed: true,
      img: '/images/onion.jpeg'
    },
    {
      id: 12,
      name: 'Rice Long Grain',
      user_id: '3',
      dateCreated: '14/08 13:00',
      expiryDate: '3/09 10:00',
      location: 'Hernbay, Auckland',
      quantity: '5 Kg',
      description: 'Restaurant closing down sale',
      email: 'thaiblue@gmail.com',
      isClaimed: false,
      img: '/images/onion.jpeg'
    },
    {
      id: 13,
      name: 'Lemons',
      user_id: '3',
      dateCreated: '14/12 8:00',
      expiryDate: '22/12 8:00',
      location: 'MtEden, Auckland',
      quantity: '20',
      description: 'Fresh off my lemon tree in my garden',
      email: 'karen@gmail.com',
      isClaimed: true,
      img: '/images/onion.jpeg'
    },
    {
      id: 14,
      name: 'Frozen Pizza',
      user_id: '3',
      dateCreated: '14/08 13:00',
      expiryDate: '3/10 10:00',
      location: 'Onehunga, Auckland',
      quantity: '10',
      description: 'left overe from an event. stored at correct temperature at all time',
      email: 'brown.s@caterforall.co.nz',
      isClaimed: true,
      img: '/images/onion.jpeg'
    },
    {
      id: 15,
      name: 'White wine',
      user_id: '3',
      dateCreated: '14/08 13:00',
      expiryDate: '3/09 10:00',
      location: 'Mangere, Auckland',
      quantity: '1',
      description: 'a bottle of unopened wine',
      email: 'sam@hotmail.com',
      isClaimed: true,
      img: '/images/onion.jpeg'
    },
    {
      id: 16,
      name: 'Dried Noodle',
      user_id: '3',
      dateCreated: '14/08 13:00',
      expiryDate: '3/09 10:00',
      location: 'Mirangi Bay, Auckland',
      quantity: '5 packets',
      description: 'Changed planned, no londer wanted',
      email: 'eatwellbeing@gmail.com',
      isClaimed: true,
      img: '/images/onion.jpeg'
    },
    {
      id: 17,
      name: 'Avocado',
      user_id: '3',
      dateCreated: '1/11 17:12',
      expiryDate: '1/12 10:00',
      location: 'Bayview, Auckland',
      quantity: '9',
      description: 'Come get avocados off my tree',
      email: 'wilson@hotmail.com',
      isClaimed: false,
      img: '/images/onion.jpeg'
    },
    {
      id: 18,
      name: 'Tinned Tomato',
      user_id: '3',
      dateCreated: '3/3 18:50',
      expiryDate: '3/09 10:00',
      location: 'Titirangi, Auckland',
      quantity: '11',
      description: 'need to go asap',
      email: 'kelly@hotmail.com',
      isClaimed: true,
      img: '/images/onion.jpeg'
    },
    {
      id: 19,
      name: 'Ice Cream',
      user_id: '3',
      dateCreated: '20/07 11:00',
      expiryDate: '19/09 11:00',
      location: 'Henderson, Auckland',
      quantity: '5 kg',
      description: 'catering size strawberry icecream',
      email: 'rodrigo@xtra.com',
      isClaimed: true,
      img: '/images/onion.jpeg'
    },
    {
      id: 20,
      name: 'Lettuce',
      user_id: '3',
      dateCreated: '7/05 7:10',
      expiryDate: '14/05 10:00',
      location: 'Stonefield, Auckland',
      quantity: '10',
      description: 'fresh iceberg lettuce. pick up by tomorrow please',
      email: 'william@wholesomecater.com',
      isClaimed: true,
      img: '/images/onion.jpeg'
    }
  ])
